### ISSUE TITLE
Meteor 3.0 compatibility

### ISSUE THREAD

**Issue by StorytellerCZ** [zodern/meteor-types#11]
When trying to upgrade to Meteor 3.0-alpha.16 it throws error pointing to this packages:

```
=> Errors while initializing project:

While loading plugin `types` from package `zodern:types`:
node:internal/modules/cjs/loader:1075:15: Cannot find module 'fibers/future'
Require stack:
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/compiler.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/packaging/package-client.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/packaging/catalog/catalog-remote.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/packaging/catalog/catalog.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/packaging/tropohouse.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/meteor-services/config.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/meteor-services/auth.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/utils/http-helpers.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/packaging/warehouse.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/cli/main.js
-
/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-alpha.16.on016t.br7mm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/index.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
at Function.resolve (node:internal/modules/cjs/helpers:116:19)
at Object.require (/tools/isobuild/bundler.js:2134:34)
at packages/meteor.js:96:20
at packages/meteor.js:266:4
at packages/meteor.js:1380:3

```

**Comment by zodern** [comment]
We publish zodern:types with Meteor 1.4 to ensure the best compatibility with older Meteor versions. I've considered two ways to fix this:

- remove `modules` from zodern:types, and use globals instead
- update Meteor 3 to stub fibers for old versions of the `meteor` package (the fibers import works, but all of the fiber methods would throw saying that fibers is not supported in Meteor 3). This should allow older build plugins that do not use fibers to work in Meteor 3

**Comment by zodern** [comment]
I opened a PR for Meteor 3 that allows zodern:types to work without changes: https://github.com/meteor/meteor/pull/12860

**Comment by StorytellerCZ** [comment]
Since the PR has been merged into Meteor, it is resolved right now, though the question is long-term solution.
